openapi: 3.0.0
info:
  version: "1.0"
  title: "OpenAPI Test"
  description: Specs for OpenAPI Test
  license:
    name: Apache
  termsOfService: https://example.com/terms/
servers:
  - url: https://dev.example.com
    description: Development Server
  - url: https://prod.example.com
    description: Production Server
  - url: https://qa.example.com
    description: QA Server
paths:
  /v1/customers:
    get:
      responses:
        "200":
          description: List of All Customers

  /v1/products:
    get:
      responses:
        "200":
          description: List of available products
        "404":
          description: No products in stock